.github/workflows/config.yml
Added inputs to the workflow dispatch action
=> feat: added inputs to the test workflow dispatch action

proxies/nodejs/app.ts
Add Location to ctx response after creating and change the status to 201
=> Dvc 5164 add location

.gitignore, proxies/nodejs/app.ts, proxies/nodejs/entityTypes.ts, proxies/nodejs/handlers/client.ts, proxies/nodejs/handlers/user.ts, proxies/nodejs/package.json, proxies/nodejs/yarn.lock
* add user endpoint
* move client handler to a new file
* add types
=> feat: add user endpoint

.eslintrc.json, .husky/pre-commit, harness/types/capabilities.ts, package.json, proxies/nodejs/app.ts, yarn.lock
Added a pre-commit rule to run `eslint` and fix any linting errors
=> chore: add linting husky and precommit

.github/workflows/config.yml, .gitignore, ci-config.js, harness/features/variable.cloud.test.ts, harness/helpers.ts, harness/mockServer/index.ts, harness/nock.test.ts, harness/types/capabilities.ts, jest-environment.ts, package.json, proxies/nodejs/handlers/client.ts, proxies/nodejs/handlers/location.ts, proxies/nodejs/tsconfig.json, yarn.lock
- Added helper methods to create client, user
- Added helper method to run tests for different variable types
- Added tests for cloud mode variable calls
=> chore: variable cloud tests

harness/mockData/config.ts, harness/mockData/features.ts, harness/mockData/variables.ts, package.json, yarn.lock
- use our types package to make the mock data follow type definitions, hopefully catching errors with incorrectly defined data
=> add type safety to mock data

proxies/nodejs/handlers/location.ts
- some cleanup to the parse location function to make it clearer how the URL is decomposed
=> cleanup parse location

harness/features/initialize.cloud.test.ts, harness/features/initialize.local.test.ts
client initialization tests working
=> chore: tests for client initialize

proxies/nodejs/handlers/location.ts, proxies/nodejs/handlers/user.ts
move location to /command/commandName/id from /command/entityType/id
=> cleanup nodejs proxy server 

harness/features/initialize.cloud.test.ts, harness/features/initialize.local.test.ts, harness/features/variable.cloud.test.ts, harness/helpers.ts
- create TestClient abstraction to handle creating a test class and keeping track of its IDs and URLs so that tests dont have to
=> add test client helper

harness/features/allVariables.cloud.test.ts, harness/features/allVariables.local.test.ts, harness/features/variable.cloud.test.ts, harness/helpers.ts, harness/mockServer/index.ts, proxies/nodejs/handlers/location.ts
fix nodejs proxy being able to properly invoke async commands
chore: change error structure
=> bug: Nodejs proxy async fix

harness/types/sdks.ts, proxies/python/app.py, proxies/python/handlers/client.py, proxies/python/handlers/command.py, proxies/python/handlers/config.py, proxies/python/handlers/user.py, proxies/python/helpers/camelcase.py, proxies/python/helpers/entity_types.py
- add endpoint for handling commands issued to a location
- reorganize route handlers into their own files
=> handle commands endpoint python

harness/features/allFeatures.cloud.test.ts, harness/features/allFeatures.local.test.ts, harness/features/allVariables.cloud.test.ts, harness/features/allVariables.local.test.ts, harness/features/initialize.cloud.test.ts, harness/features/initialize.local.test.ts, harness/features/variable.cloud.test.ts, harness/features/variable.local.test.ts, harness/helpers.ts
- update test helpers to check command succeeded by default
- add explicit override when command is expected to fail
- update all tests to pass override when needed
=> expect commands to succeed by default unless expected to fail

proxies/dotnet/Controllers/Client.cs, proxies/dotnet/Dockerfile, proxies/dotnet/Program.cs, proxies/dotnet/dotnet.csproj
- update SDK versions to resolve incompatible versions
- write /client endpoint to init cloud vs. local bucketing SDK
- still getting issues with wasmtime working locally and on the docker image...
=> DVC-5431 client endpoint dotnet

.gitignore, proxies/dotnet/Controllers/User.cs, proxies/dotnet/Models/ClientRequestUser.cs
Implement `user` endpoint for the dotnet proxy server.
=> feat: user endpoint dotnet

harness/features/initialize.local.test.ts, harness/helpers.ts, proxies/nodejs/entityTypes.ts, proxies/nodejs/handlers/client.ts
* Moved `enableCloudBucketing` option out of NodeJS SDK options to align with other SDKs
=> move enableCloudBucketing option out of SDK options

proxies/java/build.gradle, proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java, proxies/java/src/main/java/com/dvc_harness/proxy/data/DataStore.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/ClientOptions.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/ClientRequestBody.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/MessageResponse.java
- add `/client` endpoint for creating new Java clients
=> add client endpoint for java proxy

harness/helpers.ts
- apply the same guarantee that the request succeeded by default for user POST requests
=> expect user request to succeed by default

proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java, proxies/java/src/main/java/com/dvc_harness/proxy/controller/UserData.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/UserData.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/UserRequestBody.java
I only added the fields that were actively using to the builder in the endpoint. I can add the rest if we want, it just gets unruly
=> Dvc 5462 user endpoint

harness/features/allFeatures.cloud.test.ts, harness/features/allFeatures.local.test.ts, harness/features/allVariables.cloud.test.ts, harness/features/allVariables.local.test.ts, harness/features/initialize.cloud.test.ts, harness/features/initialize.local.test.ts, harness/features/track.cloud.test.ts, harness/features/track.local.test.ts, harness/features/variable.cloud.test.ts, harness/features/variable.local.test.ts, harness/helpers.ts, proxies/nodejs/handlers/user.ts, proxies/nodejs/package.json, proxies/nodejs/yarn.lock
- introduce tests checking for DVCUser creation / validation
- move all invalid user tests to "data validation" test suite
- introduce "untyped" capability to enable/disable data validation tests
=> DVC-5558 user creation tests

harness/features/allFeatures.local.test.ts, harness/features/initialize.cloud.test.ts, harness/features/initialize.local.test.ts, harness/features/track.cloud.test.ts, harness/features/track.local.test.ts, harness/features/variable.cloud.test.ts, harness/helpers.ts
Added exception message helper method to check if exception message exists.
=> chore: added helper for comparing exception messages

proxies/dotnet/Controllers/Location.cs
Handle null values for "value" in c# proxy
=> handle null value jtoken

proxies/dotnet/Controllers/Location.cs
- delete c# client when close called to allow garbage collection
in the future this should be its own endpoint
=> Delete client on close

harness/features/allVariables.cloud.test.ts
this fixes the failing tests on https://github.com/DevCycleHQ/dotnet-server-sdk/pull/63
=> Fix allVariables failure case test

proxies/go/app.go, proxies/go/go.mod, proxies/go/go.sum, proxies/go/handler_command.go
- add basic JSON parsing and introduce mux router + the command endpoint
=> add json parsing for command endpoint

harness/types/capabilities.ts, harness/types/sdks.ts
* add Go sdk to list of sdks to test
* add Go sdk capabilities
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19PYQmWiURHcZfApLrxG0KEXDT0Lq09Po%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=PyfTEGN)
=> Add Go SDK to list of SDKs to test

proxies/go/app.go, proxies/go/handler_client.go, proxies/go/handler_command.go
this ticket isn't supposed to include parsing user and event params but it ended up being surprisingly simple so i just did it here
=> Add location endpoint to go proxy

proxies/go/handler_command.go
blocked until https://github.com/DevCycleHQ/go-server-sdk/pull/25/files is merged
=> Dvc 5860 - Use ReadOnlyVariable for allVariables in go proxy

harness/features/variable.local.test.ts
- exact match the variable fields rather than expecting an object containing stuff
=> exact match the variable data for local variable test

harness/features/allFeatures.local.test.ts
Increase config polling interval to prevent unintended requests during these tests.
=> fix allfeatures flake

docker-compose.yml, harness/types/sdks.ts, proxies/java/Dockerfile
**Commented out Go proxy**
- to bypass the errors and not interfere with the parallel work on the issues
=> [chore] change the java proxy to amd64 base images to run and test locally

proxies/go/handler_command.go
- fix passing "nil" to reflect methods
- nil cant be used directly for most argument types (e.g. you can't pass "nil" when a string is expected)
- convert any nil param from the harness into an appropriate "zero value" for the argument type. The zero value for a string is `""` for example.
=> fix handling nil values in params for go

harness/features/initialize.local.test.ts
- test whether SDK will ignore a config that contains invalid data but is valid JSON
=> test receiving invalid data from valid json

proxies/java/Dockerfile, proxies/java/build.gradle, proxies/java/settings.gradle, proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/ClientOptions.java
- adds commented out lines to run the Test Harness Java Proxy with the local version of the SDK
=> [chore] add support for Java test harness running in local mode

harness/features/variable.local.test.ts, jest-setup.js, jest.config.ts, package.json, tsconfig.json, yarn.lock
- add `jest-extended` to get some extra matchers
- match on every expected field of the event object rather than doing a partial match
- this tests that an empty featureVars object is sent correctly
=> strengthen variable event tests to check for every field

harness/features/variable.local.test.ts
- modify uninitialized variable tests to add two different cases: test uninitialized due to request delay, and uninitialized due to "500" error on config request
- expect that an aggVariableDefaulted event will be triggered for each variable call
=> test for uninitialized event sending

docker-compose.yml
Allows other harnesses to pass
=> Disable ruby proxy.

docker-compose.yml, harness/types/sdks.ts, package.json, proxies/java/Dockerfile, proxies/java/build.gradle, proxies/java/settings.gradle, proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java, proxies/java/src/main/java/com/dvc_harness/proxy/data/DataStore.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/AsyncErrorResponse.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/ClientOptions.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/CommandResult.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/EntityTypes.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/ExceptionResponse.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/LocationParam.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/LocationParamType.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/LocationRequestBody.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/LocationResponse.java
- changes for Java SDK testing
- Currently only enabled for LOCAL mode for Java SDK
=> Test Harness Updates for Java Server SDK

README.md, package.json, scripts/use-local.sh
- add a script that automatically checks out a commit which contains local configuration for all current SDKs
- add instructions on how to use it
=> add script to check out local configuration automatically

.github/workflows/config.yml, action.yml, package.json
Reverts DevCycleHQ/test-harness#217
=> Revert "DVC-6514 Adding yarn build:docker step to build docker images using depot.dev"

harness/features/multithreading.local.test.ts
test that setting client custom data works in multithreaded mode
=> add multithreading test for setting client custom data

.github/workflows/config.yml, .gitignore, action.yml, package.json, yarn.lock
See https://github.com/DevCycleHQ/test-harness/actions/runs/4568276341/jobs/8063356397 for sample output.
Uses https://github.com/dorny/test-reporter
=> Show jest test results nicely in Github

README.md, docker-compose.yml, docs/LOCAL.md, proxies/go/.gitignore, proxies/go/README.md
Also includes Adam's fix for newer docker-compose versions.
=> Local mode docs improvements

docs/LOCAL.md, harness/features/variable.cloud.test.ts, harness/features/variable.local.test.ts, harness/helpers.ts, harness/types/capabilities.ts, jest.config.ts, package.json, proxies/dotnet/Controllers/Location.cs, proxies/go/app.go, proxies/go/handler_command.go, proxies/nodejs/handlers/client.ts, proxies/nodejs/package.json, proxies/nodejs/yarn.lock, proxies/openfeature-nodejs/handlers/location.ts, proxies/ruby/app.rb
- updated tests for new `variableValue()` SDK methods
- Update proxys to handle calling `variableValue()` methods
=> DVC-7319 adding variableValue tests 

.github/workflows/config.yml, docker-compose.yml, docs/LOCAL.md, harness/features/track.local.test.ts, harness/features/variable.local.test.ts, harness/types/capabilities.ts, harness/types/sdks.ts, jest-testcontainers-config.js, jest.config.ts, proxies/java/Dockerfile, proxies/java/HELP.md, proxies/java/README.md, proxies/java/build.gradle, proxies/java/install.sh, proxies/java/settings.gradle, proxies/java/src/main/java/com/dvc_harness/proxy/ProxyApplication.java, proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java, proxies/java/src/main/java/com/dvc_harness/proxy/data/DataStore.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/AsyncErrorResponse.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/ClientRequestBody.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/CommandResult.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/ExceptionResponse.java
updated the proxy, build process and docker container to bring it up to date and work with the Java Server SDK
=> DVC-7132 Java Server SDK support

docker-compose.yml, harness/features/allFeatures.cloud.test.ts, harness/features/allVariables.cloud.test.ts, harness/features/initialize.cloud.test.ts, harness/features/track.cloud.test.ts, harness/helpers.ts, harness/types/sdks.ts, jest.config.ts, proxies/python/Dockerfile, proxies/python/README.md, proxies/python/app.py, proxies/python/handlers/client.py, proxies/python/handlers/command.py, proxies/python/handlers/user.py, proxies/python/helpers/entity_types.py, proxies/python/helpers/to_dict.py, proxies/python/install.sh
- Finished missing functionality in the python proxy
- got all the tests working for the cloud SDK
- fixed the Dockerfile to load versions and SHA code
=> DVC-7569 enable python sdk

ci-config.ts
Reverts DevCycleHQ/test-harness#255
=> Revert "remove process.env.DOCKER_HOST_IP to try and fix nodeJS SDK"

package.json
- adds an output of full logs from docker builds during CI run
=> Output full logs for docker build in CI

harness/types/capabilities.ts, proxies/python/app.py, proxies/python/handlers/client.py, proxies/python/handlers/command.py
Changes to the test harness and python proxy to support the new local bucketing SDK
=> Support for Python Local SDK

proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java, proxies/java/src/main/java/com/dvc_harness/proxy/data/DataStore.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/CommandResult.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/LocationRequestBody.java, proxies/java/src/main/java/com/dvc_harness/proxy/models/UserData.java
This updates the test harness to match the changes in this PR: https://github.com/DevCycleHQ/java-server-sdk/pull/92
See [JIRA: DVC-8028](https://taplytics.atlassian.net/browse/DVC-8028)
**Note:** I have run these changes locally with the updated branch of the Java SDK and the test harness passes without errors. I'd like to merge this in first, event though it will be broken so that we can confirm the java server sdk PR above passes before we merge
=> chore: Update Java proxy to match DVC -> DevCycle refactoring

proxies/dotnet/Controllers/Location.cs, proxies/dotnet/dotnet.csproj
Also reformat according to .NET standards.
=> fix: All .NET functions are async now; and need to be awaited.

package.json, proxies/nodejs/package.json, proxies/nodejs/yarn.lock, proxies/openfeature-nodejs/handlers/client.ts, proxies/openfeature-nodejs/install.sh, proxies/openfeature-nodejs/package.json, proxies/openfeature-nodejs/yarn.lock, yarn.lock
feat: update OpenFeature NodeJS test harness to use new getOpenFeatureProvider() method
chore: update to nodejs sdk 1.21.0
=> feat: update OpenFeature NodeJS test harness to use new getOpenFeatureProvider() method

harness/helpers.ts
trying same fix as: https://github.com/DevCycleHQ/js-sdks/pull/805
=> fix: global.fetch failure on tests

harness/features/multithreading.local.test.ts, harness/features/variable.local.test.ts
- adjust the expectations to what they actually are named in the SDK
=> fix expected default reasons

harness/features/multithreading.local.test.ts, harness/features/variable.local.test.ts, harness/helpers/events.ts, harness/types/capabilities.ts
Add tests checking for etag reporting in event metadata
=> Test for etag metadata

harness/features/initialize.local.test.ts, harness/features/variable.local.test.ts, harness/helpers/events.ts
- add tests for tracking rayid of config response
=> Rayid tracking

harness/features/initialize.local.test.ts
- Added a test that checks whether the variable call will default if the first config fetch fails, but will return a value after the polling picks up a config. 
- Test passes for all except node/of-node, which will be fixed with this change https://github.com/DevCycleHQ/js-sdks/pull/866
=> add a test that ensures the sdk recovers when the initial config fails

.github/workflows/config.yml
=> chore: change test harness action branch rules

harness/features/allFeatures.local.test.ts, harness/features/allVariables.local.test.ts, harness/features/initialize.local.test.ts, harness/features/track.local.test.ts, harness/features/variable.local.test.ts, harness/types/capabilities.ts
=> chore: cleanup local bucketing capability supported by all SDKs

harness/types/capabilities.ts, proxies/php/php-proxy/index.php
=> feat: add variableValue support to PHP proxy

harness/features/variable.cloud.test.ts, harness/features/variable.local.test.ts, harness/types/capabilities.ts
=> chore: cleanup variableValue capability

harness/features/variable.local.test.ts, harness/helpers/helpers.ts, harness/types/capabilities.test.ts, harness/types/capabilities.ts, harness/types/sdks.ts, jest-global.ts, jest.config.ts
=> feat: add ability to load capabilities from env vars

harness/types/capabilities.ts
Reverts DevCycleHQ/test-harness#463
=> Revert "chore: Add capabilities"

proxies/nodejs/handlers/client.ts, proxies/nodejs/package.json, proxies/nodejs/yarn.lock, yarn.lock
=> chore: update braces dependancy

.github/workflows/config.yml
Explicitly install docker compose to fix missing docker errors
=> Install docker-compose explicitly

harness/types/capabilities.ts
=> chore: added v2 capabilities for the sdks

harness/features/bootstrapping.test.ts
=> chore: updated bootstrapping code to support v2 capabilities

package.json, yarn.lock
=> fix: add resolution for cross-spawn to fix vuln

action.yml, harness/features/track.local.test.ts, harness/helpers/events.ts, harness/types/capabilities.ts, package.json, proxies/nodejs/package.json, proxies/nodejs/yarn.lock, proxies/openfeature-nodejs/package.json, proxies/openfeature-nodejs/yarn.lock, yarn.lock
=> feat: add 'sdkPlatform' test capability for OF nodeJS

harness/types/capabilities.ts
=> chore: cleanup node of capabilities

proxies/java/Dockerfile
=> chore: update java gradle docker version

proxies/nodejs/yarn.lock, proxies/openfeature-nodejs/yarn.lock, yarn.lock
=> chore: update koa

proxies/php/php-proxy/composer.lock
Fixes php tests failing because of dep updates
=> chore: update lockfile

proxies/nodejs/Dockerfile, proxies/openfeature-nodejs/Dockerfile
=> chore: update node.js docker file deps for js-sdks

package.json, yarn.lock
=> chore: update tar-fs dep

harness/mockServer/index.ts, package.json, proxies/nodejs/app.ts, proxies/nodejs/handlers/client.ts, proxies/nodejs/handlers/location.ts, proxies/nodejs/package.json, proxies/nodejs/yarn.lock, proxies/openfeature-nodejs/app.ts, proxies/openfeature-nodejs/handlers/client.ts, proxies/openfeature-nodejs/handlers/location.ts, proxies/openfeature-nodejs/package.json, proxies/openfeature-nodejs/yarn.lock, yarn.lock
=> chore: update koa deps, typescript, yarn

harness/features/allVariables.cloud.test.ts, harness/features/allVariables.local.test.ts, harness/features/track.local.test.ts, harness/mockData/variables.ts, harness/types/capabilities.ts
=> feat: add variablesFeatureId capability and update tests to handle for it

.github/workflows/config.yml
=> chore: try 8 core runner

harness/features/multithreading.local.test.ts, harness/features/variable.cloud.test.ts, harness/helpers/events.ts, harness/helpers/helpers.ts, harness/mockData/variables.ts, harness/types/capabilities.test.ts, harness/types/capabilities.ts
- remove debug logs
- update to use helper functions
=> feat: update test-harness to pass for other languages

package.json, proxies/nodejs/package.json, proxies/nodejs/yarn.lock, proxies/openfeature-nodejs/package.json, proxies/openfeature-nodejs/yarn.lock, yarn.lock
=> chore: update deps: koa, tmp
