- proxies/nodejs/app.ts
- proxies/nodejs/entityTypes.ts
- proxies/nodejs/handlers/client.ts
- proxies/nodejs/handlers/location.ts
- proxies/nodejs/handlers/user.ts
- call methods and format return values
- assumptions: 
- the call will only be made on `client` and `user` at the moment, 
- callbacks not yet supported 
- the POST `/location` call is being on a function that exists on the type
- entityType just shows object, will be accurate after all object types are well defined 
Tested on the following test data:
```js
const testClientData = [
{
"clientId": 1,
"sdkKey": "<SDKKEY>",
"options": {},
},
{
clientId: 2,
sdkKey: "<SDKKEY>",
options: {},
}
]
const testUserData = [
{
"user_id": "1",
"name": "user1",
isAnonymous: false,
},
{
"user_id": "2",
"name": "user2",
isAnonymous: false,
}
]
testClientData.forEach(async (clientData) => {
const client = await initialize(clientData.sdkKey, clientData.options).onClientInitialized() …
```
> [DVC-5168] feat: add location call to proxy server 

- .github/workflows/config.yml
- ci-config.js
- ci-config.ts
- docker-compose.yml
- harness/features/variable.cloud.test.ts
- harness/helpers.ts
- package.json
- proxies/nodejs/Dockerfile
- proxies/nodejs/install.sh
- yarn.lock
If a sha has been passed in from `workflow_dispatch`, then we write it to an `.env` file and use it to checkout a specific commit of the nodejs sdk and install that version after building with nx
> feat: checkout sha of node js sdk if given from workflow

- .github/workflows/config.yml
`.env` file gets created before checkout of the repo occurs, placing it in the wrong folder. Moved it to after checkout step.
> fix: moved writing env to after checkout

- harness/helpers.ts
- override the global fetch function to always log the full error object as well as throw it
> override global fetch to log full exception

- harness/features/allFeatures.cloud.test.ts
- harness/features/allFeatures.local.test.ts
- harness/features/allVariables.cloud.test.ts
- harness/features/allVariables.local.test.ts
- harness/features/initialize.cloud.test.ts
- harness/features/initialize.local.test.ts
- harness/features/track.cloud.test.ts
- harness/features/track.local.test.ts
- harness/features/variable.cloud.test.ts
- harness/features/variable.local.test.ts
- harness/helpers.ts
- jest.config.js
- proxies/nodejs/entityTypes.ts
- proxies/nodejs/handlers/location.ts
- proxies/nodejs/package.json
- proxies/nodejs/yarn.lock
Separate the cloud and local clients into two separate test helpers
Both helpers pass the appropriate option to the proxy when calling `createClient` to make the right kind of client
The call methods (callVariable, callAllVariables etc.) correctly set the `isAsync` property to true or false depending on the client.
Also fixed some sources of errors happening on the proxy server:
- initialize tests now respond to CDN request with a valid config
- event API mocking now always returns 201 instead of 200
The "wait for initialize" method will now make sure the request was successful and that the SDK did not throw an error. The same will happen for track unless you specify that you're expecting it to fail.
> Add cloud test client helper

- harness/features/variable.cloud.test.ts
- harness/features/variable.local.test.ts
- update variable tests to expect a correct `type` field on the DVCVariable object.
> expect variable type field in harness tests

- harness/features/variable.local.test.ts
- harness/helpers.ts
- harness/nock.ts
Reset nock scopes between test cases so that an unmatched interceptor won't continue to exist and continue to not be matched on all following test cases after it's missed the first time.
This should make it easier to tell which test case actually failed and which ones are just failing due to a cascade of unsatisfied mocks.
Also reorganize the await request statements in the variable local tests so that the assertion on the response body does not prevent it from waiting for the event request to come in. This prevents further tests from failing due to not waiting for the event request from a test case whose response body was wrong (but where the SDK sends an event regardless)
> DVC-5572 nock reset scopes

- harness/features/allFeatures.cloud.test.ts
- harness/features/allFeatures.local.test.ts
- harness/features/allVariables.cloud.test.ts
- harness/features/allVariables.local.test.ts
- harness/features/track.cloud.test.ts
- harness/features/track.local.test.ts
- harness/features/variable.cloud.test.ts
- harness/features/variable.local.test.ts
- harness/helpers.ts
Use the new location endpoint params on all tests to simplify and consolidate user creation and event creation errors.
> chore: change location endpoint usage

- proxies/dotnet/Controllers/Client.cs
- proxies/dotnet/Controllers/Location.cs
- do not override flush interval if the value is 0 (which is the default when not set)
- cast numbers to `long` to temporarily fix integer variable tests
> fix event flush interval override and numberic casting

- proxies/dotnet/Controllers/Location.cs
Only respond 404 when entity location is not valid.
Otherwise respond with any exception thrown from parsing params.
This will correctly catch errors with constructing User and Event objects
> fix proxy error handling

- proxies/dotnet/Controllers/Location.cs
The naming of the method is based on the `Disposable` pattern in C# so it's a platform-specific difference we should abstract over
> call dispose when close is called for C#

- proxies/dotnet/Controllers/Location.cs
Prevent calling `await` if the result is `null` to avoid a cryptic error.
> null check await call

- harness/features/initialize.local.test.ts
Can't call close on a client that was never created
> remove close call on invalid client tests

- harness/features/variable.local.test.ts
- reorder the client initialization setup for variable local tests
- fix the URL on the scope interceptor
> Fix variable local ordering

- docs/GUIDE.MD
- harness/features/variable.cloud.test.ts
- harness/features/variable.local.test.ts
Added comments to local and cloud variable tests, along with a `GUIDE.md` to prescribe how to write harness tests.
> chore: added a guide.md to prescribe how to write test harness tests

- docker-compose.yml
- proxies/go/Dockerfile
- proxies/go/install.sh
- install Go from Github sha or specific version
- update dockerfile to use builder image and call the install script
- hook up to docker compose
> install from github sha for Go proxy

- proxies/go/handler_client.go
- proxies/go/handler_command.go
these 2 changes get allFeatures cloud passing completely and allVariables cloud mostly passing except for the 400-level exceptions aren't thrown (making a ticket for that now)
> Add BucketingAPIURI override and parse empty map results as {} instead of null

- proxies/go/handler_command.go
Fix variable serialization by explicitly casting it when we know its a Variable object
> fix serializing variable responses on go

- harness/features/initialize.local.test.ts
- harness/mockData/index.ts
- harness/mockData/users.ts
- test that the cached config is used when the reply is 304 not modified
- test that the cached config is used when the reply is a failure, but that it retries that request once
- test that the cached config used when the reply is not valid JSON
> test config fetching with etag and failure behaviour

- harness/features/initialize.local.test.ts
- add test checking that SDK will stop making config polling requests when it gets a 403 (invalid SDK key)
> add test for stopping polling interval on 403 error

- package.json
Issue: If running tests with node v16, error is found `ReferenceError: fetch is not defined`
- set minimum node version(v18) for test harness to let tests run properly
> Dvc 5965 set minimum node version for test harness

- harness/features/clientCustomData.test.ts
- harness/helpers.ts
- harness/types/capabilities.ts
- proxies/go/handler_command.go
- add tests for setClientCustomData
- fix Go proxy to respond with error when a method with an error return value sets that value to something
> DVC-6142 client custom data tests

- harness/features/initialize.local.test.ts
- harness/helpers.ts
As some SDKs will log either: 
- `Missing SDK key! Call build with a valid SDK key`
- `Missing SDK key! Call initialize with a valid SDK key`
> DVC-6222 fix initialize SDK tests with new expectErrorToContain()

- harness/features/variable.local.test.ts
SDKs are incorrectly sending the "date" field in addition to client date. Make the test allow either empty field or a string until this is fixed.
Also allow some inconsistently specified fields while there are outstanding bugs to fix them
> allow empty date field, and others

- proxies/java/src/main/java/com/dvc_harness/proxy/controller/ProxyController.java
- proxies/java/src/main/java/com/dvc_harness/proxy/models/AsyncErrorResponse.java
- proxies/java/src/main/java/com/dvc_harness/proxy/models/CommandResult.java
- If `isAsync` return an async error
- If null is passed as a param, don't handle this when parsing params. Pass the null value to the sdk and return the sdk error
> [fix] Return java sdk errors from proxy

- harness/features/allFeatures.cloud.test.ts
- harness/features/allFeatures.local.test.ts
- harness/features/allVariables.cloud.test.ts
- harness/features/allVariables.local.test.ts
- harness/features/clientCustomData.test.ts
- harness/features/initialize.local.test.ts
- harness/features/track.cloud.test.ts
- harness/features/track.local.test.ts
- harness/features/variable.cloud.test.ts
- harness/features/variable.local.test.ts
- harness/helpers.ts
- harness/mockServer/index.ts
- keep track of the current client instance being used for tests
- keep a record of which test case name created that client
- throw error if a test client is created outside the scope of an individual test case
- change all test files to create a new client for each test
- add the test case name that caused the unmatched nock scope error to the message that is thrown (if the test case is different than the current one)
- automatically call the client `close` method at the end of each test case
- remove all manual calls to client.close
> track unmatched scopes and log the test case name that caused them

- docker-compose.yml
- harness/helpers.ts
- harness/types/capabilities.ts
- harness/types/sdks.ts
- proxies/go/Dockerfile
This is actually an alternate build of the existing go-server-sdk, so we
have to trick the tests a little to allow this.
Tests pass locally, and there's nothing really different between the two right now, so I expect this to work on main.
> DEV-6791: Add configuration for Go native SDK

- harness/features/initialize.local.test.ts
- harness/features/track.local.test.ts
- harness/features/variable.local.test.ts
- harness/helpers.ts
- harness/types/capabilities.ts
This should get the Go native SDK tests passing in a very minimal way.  We can add back capabilities as we get more things working.
> Limit capabilities for Go native SDK and exclude more tests

- harness/features/clientCustomData.test.ts
- harness/helpers.ts
- harness/types/capabilities.ts
This turns the client custom data tests back on for the gonative SDK.
I made the events endpoint stubs only set up when events are supported - otherwise they fail the test when they're not hit.
This PR will fail until DevCycleHQ/go-server-sdk#159 is merged.
> enable client custom data tests for gonative

- README.md
- docker-compose.yml
- docs/GUIDE.MD
- harness/helpers.ts
- jest-global.ts
- jest.config.ts
This uses docker-compose's profiles support to limit which services are actually run by Jest, and adds support for a native local flow by disabling them all.
Most single SDK runs should be significantly faster since only the one image needs to be built and started.
I've uncommented the docker-compose services for the not-yet-supported SDKs, because they're now effectively disabled via profiles until we enable them in the `Sdks` enum.
> Support local flow natively and speed up single SDK runs

- harness/types/capabilities.ts
- proxies/dotnet/Controllers/Location.cs
.Net SDK now has setClientCustomData support for WASM and needs to be tested by the harness
> Add clientCustomData to dotnet SDK tests

- docs/GUIDE.MD
- harness/features/allFeatures.cloud.test.ts
- harness/features/allFeatures.local.test.ts
- harness/features/allVariables.cloud.test.ts
- harness/features/allVariables.local.test.ts
- harness/features/clientCustomData.test.ts
- harness/features/initialize.cloud.test.ts
- harness/features/initialize.local.test.ts
- harness/features/multithreading.local.test.ts
- harness/features/track.cloud.test.ts
- harness/features/track.local.test.ts
- harness/features/variable.cloud.test.ts
- harness/features/variable.local.test.ts
- harness/helpers.ts
- harness/types/sdks.ts
- jest-global.ts
- jest-setup.js
- jest-testcontainers-config.js
- jest.config.ts
Switch from running tests for each SDK using `describe.each` to using Jest "projects" which each define the SDK that should be tested.
TODO: figure out how to compartmentalize the docker compose files for each project to only run the appropriate proxy container.
> use jest projects to run sdk tests in parallel

- docker-compose.yml
- harness/features/multithreading.local.test.ts
- harness/helpers.ts
- harness/types/capabilities.ts
- harness/types/sdks.ts
- jest.config.ts
This changes the default Go tests to target the native code that will be turned on by default in DevCycleHQ/go-server-sdk#194.
I modified the multithreading tests as they had assumptions built in around the division of event into multiple batches by the multiple WASM workers. That's no longer true with the native Go SDK.
I've tested this locally against [a354811](https://github.com/DevCycleHQ/go-server-sdk/pull/194/commits/a3548118f75b23f224292928f60fa3b3f7693fd3) and confirmed that both Go and GoWASM pass.
> DVC 7423: Update to test default native bucketing in Go SDK

- proxies/python/Dockerfile
Resolves an error when trying to import python wasmtime, since alpine doesn't use libc.
> DVC-7920: Stop using alpine container for python proxy

- proxies/python/install.sh
fixed issue where GITHUB SHA env var wasn't triggering a proper initialization of the proxy
> [fix] Python Proxy not pulling SHA properly

- proxies/dotnet/Controllers/Client.cs
- proxies/dotnet/Controllers/Location.cs
- proxies/dotnet/DataStore.cs
- proxies/dotnet/Models/ClientRequestEvent.cs
- proxies/dotnet/Models/ClientRequestUser.cs
This updates the test harness to match the changes in this PR: https://github.com/DevCycleHQ/dotnet-server-sdk/pull/102
See [JIRA: DVC-8029](https://taplytics.atlassian.net/browse/DVC-8029)
Note: I have run these changes locally with the updated branch of the DotNet SDK and the test harness passes without errors. I'd like to merge this in first, event though it will be broken so that we can confirm the dotnet server sdk PR above passes before we merge
> chore: Update DotNet proxy to match DVC -> DevCycle refactoring

- proxies/nodejs/handlers/location.ts
- proxies/nodejs/yarn.lock
- proxies/openfeature-nodejs/handlers/location.ts
- proxies/openfeature-nodejs/yarn.lock
I installed the latest `@devcycle/nodejs-server-sdk` and `@devcycle/openfeature-nodejs-provider`, which pulled in new versions of `protobufjs`. I switched the versions in the package.json files back to `*` instead of specific versions so we don't have to keep bumping it for testing test harness changes.
I also fixed a few small type signature issues in the proxies for nodejs and of-nodejs.
> fix: Upgrade protobufjs via latest version of node SDKs

- jest-environment.ts
- jest-global.ts
- jest.config.ts
- package.json
- yarn.lock
- switch to fork of jest-testcontainers for dependency upgrades
- Bump word-wrap from 1.2.3 to 1.2.4
> fix: Upgrade jest-testcontainers and bump word-wrap (DVC 9294)

- package.json
- yarn.lock
Fixes yaml vulnerability via secondary dependency. `yarn lint-staged` seems to still work when I run it locally.
> fix: Upgrade lint-staged to 15.0.2

- harness/features/initialize.local.test.ts
- harness/features/variable.local.test.ts
- harness/helpers/events.ts
- harness/mockServer/index.ts
- add new test for config etag changing and verify bucketing result changes
- also check the etag being reported in event metadata
- update the mock server to properly forward headers send by nock response
> add test for config etag caching and reporting

- harness/features/bootstrapping.test.ts
The field name was wrong in the tests, the actual name being used by the config service is `clientSDKKey`
> rename to client sdk key

- harness/features/clientCustomData.test.ts
- harness/features/initialize.local.test.ts
- harness/features/track.local.test.ts
- harness/features/variable.local.test.ts
- harness/helpers/events.ts
- harness/types/capabilities.ts
> chore: cleanup events capability supported by all SDKs

- harness/features/initialize.local.test.ts
- harness/helpers/helpers.ts
- harness/mockServer/index.ts
- wait for config requests rather than arbitrary amounts of time
- remove redundant config request handlers that should never be triggered given the setup for the test
- remove `.times(1)` specifier as it is redundant
- fix stack trace for errors thrown from event handler timeout so its possible to find which event call triggered the error
- add headers to request debug log
> Improve etag test

- harness/features/variable.local.test.ts
- update the variable.local test to include v2 config url
> bug: update the variable local test for v2 configs

- proxies/dotnet/Controllers/Client.cs
not if the initialization is delayed intentionally
Without this you'll get a concurrent error exception/out of bounds.
> Only throw errors if they exist 

- harness/features/initialize.local.test.ts
Timeouts on each SDK for the request/retries are different - so this sets it below them all. 
The timeouts cause a race condition based on the number of tests running/the requests handled.
> chore: Fix timeout delay

- proxies/python/handlers/command.py
Fixes [https://github.com/DevCycleHQ/test-harness/security/code-scanning/46](https://github.com/DevCycleHQ/test-harness/security/code-scanning/46)
To fix the log injection issue, we need to sanitize the user input before logging it. Specifically, we should remove any newline characters from the `command` and `parsed_params` variables to prevent log injection. We can use the `replace` method to achieve this.
1. Sanitize the `command` variable by replacing newline characters with empty strings.
2. Sanitize each element in the `parsed_params` list by replacing newline characters with empty strings.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert no. 46: Log Injection

- proxies/go/Dockerfile
- proxies/go/go.mod
Pinning test harness dockerfile will fail whenever we update the sdk - so removing the pinned version; also updating to golang 1.23 (current) for module
> Test-harness-version

- .cursor/rules/configTooling.mdc
- .cursor/rules/formatting.mdc
- .cursor/rules/gitCommitConventions.mdc
- .cursor/rules/namingConventions.mdc
- .cursor/rules/projectStructure.mdc
- .cursor/rules/testingMocks.mdc
Update all Cursor rules for project structure, testing, formatting, naming, and commit conventions.
> docs: update cursor rules

- harness/types/capabilities.test.ts
- harness/types/capabilities.ts
- jest.unit.config.ts
- package.json
- proxies/nodejs/package.json
- proxies/nodejs/yarn.lock
- proxies/openfeature-nodejs/package.json
- proxies/openfeature-nodejs/yarn.lock
- add support for per-SDK capability configuration via `SDK_CAPABILITIES` JSON object
- add and fix unit tests for SDKCapabilities
- add `jest.unit.config.ts` for running unit tests without testcontainers
- update `package.json` with `test:unit` script for unit tests without running testcontainers
> feat: add per-SDK capability config and unit test script

- README.md
- docs/LOCAL.md
- Clarify local SDK usage for NodeJS and OpenFeature proxies in LOCAL.md and README.md.
> docs: update local SDK usage instructions for NodeJS and OpenFeature proxies

- .github/workflows/update-dvc-sdk.yml
Potential fix for [https://github.com/DevCycleHQ/test-harness/security/code-scanning/49](https://github.com/DevCycleHQ/test-harness/security/code-scanning/49)
To fix the issue, we will add a `permissions` block at the root of the workflow file to explicitly define the minimal permissions required for the workflow. Based on the actions performed in the workflow, the following permissions are necessary:
- `contents: write` for committing and pushing changes to the repository.
- `pull-requests: write` for creating a pull request.
This ensures that the workflow has only the permissions it needs to function correctly, reducing the risk of unintended actions.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> chore: Potential fix for code scanning alert no. 49: Workflow does not contain permissions

- harness/features/variable.cloud.test.ts
- harness/types/capabilities.ts
- adds capabilities for Cloud Eval Reason and Eval Reason
- adds Cloud Eval Reason capability to NodeJS Cloud SDK
- update test expectations for NodeJS Cloud Bucketing `variable` tests
> chore: adds default and error eval reason checking on NodeJS Cloud Bucketing SDK

- harness/features/allVariables.cloud.test.ts
- harness/features/allVariables.local.test.ts
- harness/mockData/variables.ts
- harness/types/capabilities.ts
add expectations for node and openfeature-node for eval reason to be included in bucketing variable tests.
implemented in https://github.com/DevCycleHQ/js-sdks/pull/1091. This will fail until those changes are merged.
> chore: add eval reason capabilities for nodejs

- harness/mockData/variables.ts
- harness/types/capabilities.ts
including target_id in eval reasons so specific target can be identified
> chore: add target_id prop in eval object

- harness/features/allFeatures.local.test.ts
- harness/features/allVariables.local.test.ts
- harness/types/capabilities.test.ts
- harness/types/capabilities.ts
adding allVariables and allFeatures capabilities so of-node tests can skip these test files
- these functions are not supported by OF and the proxy was just calling devcycle sdk functions, which conflicted with capability for evalReason and caused tests to fail
- lets test-harness pass for of-node, in future it will have its own evalReasons capability for variable call only and i can undo this change
> chore: exclude of-node from allVariables/allFeatures tests

- harness/features/variable.cloud.test.ts
- harness/features/variable.local.test.ts
- harness/types/capabilities.ts
- proxies/openfeature-nodejs/handlers/location.ts
extra fields for eval reasons "details" and "target_id" can be returned from OF via the flagMetadata. 
Update proxy to return this and add expectations to the tests.
> chore: add tests for openfeature eval metadata

- harness/features/variable.cloud.test.ts
- harness/features/variable.local.test.ts
based on comment in https://github.com/DevCycleHQ/js-sdks/pull/1117 I am only setting metadata fields when they exist instead of defaulting to empty string. Updating relevant tests
> chore: handle undefined metadata

- harness/helpers/events.ts
- fix: `aggVariableEvaluated` events metadata should contain eval with a `TARGETING_MATCH` reason with a number value
> fix: update aggVariableEvaluated event metadata format

- harness/features/clientCustomData.test.ts
- to allow null and undefined for evalReason field
> chore: update client custom data eval reason expectations

- harness/types/capabilities.ts
python released with eval reason - add capabilities to be run by default
> chore: update python capabilities for eval reasons
